/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search published documents across all tenants */
        get: operations["get-search-82dab022"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrBadRequest: {
            /**
             * @description Machine-readable error code
             * @constant
             */
            code: "BAD_REQUEST";
            details?: {
                reason?: string;
            };
            /** @description Human-readable error message */
            message: string;
        };
        ErrForbidden: {
            /**
             * @description Machine-readable error code
             * @constant
             */
            code: "FORBIDDEN";
            details?: {
                reason?: string;
            };
            /** @description Human-readable error message */
            message: string;
        };
        ErrUnauthorized: {
            /**
             * @description Machine-readable error code
             * @constant
             */
            code: "UNAUTHORIZED";
            details?: {
                reason?: string;
            };
            /** @description Human-readable error message */
            message: string;
        };
        SearchResultResponse: {
            /** @description Published content */
            content: string;
            /**
             * Format: date-time
             * @description When the document was created
             */
            created_at: string;
            /** @description Document ID */
            document_id: string;
            /**
             * @description Document key
             * @example guides/install.md
             */
            key: string;
            /** @description Organizational tags */
            tags: string[];
            /** @description Owning tenant */
            tenant_id: string;
            /** @description Published version number */
            version_number: number;
        };
        SearchResultsResponse: {
            /** @description Page size */
            limit: number;
            /** @description Page offset */
            offset: number;
            /** @description The page of cross-tenant matches */
            results: components["schemas"]["SearchResultResponse"][];
            /** @description Total number of matches across all pages */
            total: number;
        };
        ValidationFieldError: {
            /** @description The field that failed validation */
            field: string;
            /** @description Description of the validation failure */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-search-82dab022": {
        parameters: {
            query?: {
                q?: string;
                limit?: string;
                offset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultsResponse"];
                };
            };
            /** @description BadRequest */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrBadRequest"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrUnauthorized"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrForbidden"];
                };
            };
        };
    };
}
