package mdast

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestFixtures parses every .md fixture and compares its mdast JSON, byte for
// byte, with the golden .json produced by remark. The golden files are
// generated by web/scripts/mdast-fixtures.mjs.
func TestFixtures(t *testing.T) {
	mds, err := filepath.Glob(filepath.Join("testdata", "*.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, md := range mds {
		if filepath.Base(md) == "README.md" {
			continue
		}
		name := base(md)
		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(md) //nolint:gosec // test-owned fixture path
			if err != nil {
				t.Fatal(err)
			}
			want, err := os.ReadFile(filepath.Join("testdata", name+".json")) //nolint:gosec // test-owned fixture path
			if err != nil {
				t.Fatalf("missing golden file: %v", err)
			}
			root, meta, err := Parse(src)
			if err != nil {
				t.Fatalf("Parse: %v", err)
			}
			got, err := canonicalJSON(root)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("mdast JSON differs from golden:\n%s", firstDiff(want, got))
			}
			checkMeta(t, name, meta)
		})
	}
}

func base(path string) string {
	b := filepath.Base(path)
	return b[:len(b)-len(filepath.Ext(b))]
}

// checkMeta compares the frontmatter a fixture returned against its golden
// <name>.meta.json. A fixture without that file must return an empty map, which
// covers every non-frontmatter fixture and the malformed-frontmatter case.
func checkMeta(t *testing.T, name string, meta map[string]any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name+".meta.json")) //nolint:gosec // test-owned fixture path
	if err != nil {
		if len(meta) != 0 {
			t.Errorf("no %s.meta.json but Parse returned metadata %v", name, meta)
		}
		return
	}
	var want any
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatalf("meta golden: %v", err)
	}
	gotJSON, err := canonicalJSON(meta)
	if err != nil {
		t.Fatalf("marshal meta: %v", err)
	}
	wantJSON, err := encodeIndent(want)
	if err != nil {
		t.Fatalf("marshal meta golden: %v", err)
	}
	if !bytes.Equal(gotJSON, wantJSON) {
		t.Errorf("metadata differs from golden:\n%s", firstDiff(wantJSON, gotJSON))
	}
}

// canonicalJSON marshals a tree the way the fixtures are written: sorted keys, a
// two-space indent, no HTML escaping of <, >, and &, and a trailing newline.
// The struct output is round-tripped through a generic value so map-key sorting
// applies at every level.
func canonicalJSON(v any) ([]byte, error) {
	raw, err := encode(v)
	if err != nil {
		return nil, err
	}
	var generic any
	if err := json.Unmarshal(raw, &generic); err != nil {
		return nil, err
	}
	return encodeIndent(generic)
}

func encode(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func encodeIndent(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// firstDiff returns a short excerpt of both sides around the first byte that
// differs, so a failure points at where the trees diverge.
func firstDiff(want, got []byte) string {
	i := 0
	for i < len(want) && i < len(got) && want[i] == got[i] {
		i++
	}
	start := i - 60
	if start < 0 {
		start = 0
	}
	win := func(b []byte) string {
		end := i + 60
		if end > len(b) {
			end = len(b)
		}
		return string(b[start:end])
	}
	return "at byte " + itoa(i) + "\n--- want ---\n" + win(want) + "\n--- got ---\n" + win(got)
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b [20]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	return string(b[i:])
}

// TestListItemSpread locks the spread rule for a case the golden fixtures do
// not exercise: a list item whose own block children are separated by a blank
// line is spread, while an item with adjacent children (a paragraph and a
// nested list) is not.
func TestListItemSpread(t *testing.T) {
	src := []byte("- first\n\n  second\n\n- lone\n  - nested\n")
	root, _, err := Parse(src)
	if err != nil {
		t.Fatal(err)
	}
	list, ok := root.Children[0].(*List)
	if !ok {
		t.Fatalf("first child is %T, want *List", root.Children[0])
	}
	spreads := make([]bool, len(list.Children))
	for i, c := range list.Children {
		li, ok := c.(*ListItem)
		if !ok {
			t.Fatalf("list child %d is %T, want *ListItem", i, c)
		}
		spreads[i] = li.Spread
	}
	want := []bool{true, false}
	if len(spreads) != len(want) || spreads[0] != want[0] || spreads[1] != want[1] {
		t.Errorf("item spreads = %v, want %v", spreads, want)
	}
}

// BenchmarkParsePage parses the realistic page fixture.
func BenchmarkParsePage(b *testing.B) {
	src, err := os.ReadFile(filepath.Join("testdata", "page.md"))
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.SetBytes(int64(len(src)))
	for b.Loop() {
		if _, _, err := Parse(src); err != nil {
			b.Fatal(err)
		}
	}
}
