package mdast

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/zoobz-io/barbara/internal/treejson"
)

// TestFixtures parses every .md fixture and compares its mdast JSON, byte for
// byte, with the golden .json produced by remark. The golden files are
// generated by web/scripts/mdast-fixtures.mjs.
func TestFixtures(t *testing.T) {
	mds, err := filepath.Glob(filepath.Join("testdata", "*.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, md := range mds {
		if filepath.Base(md) == "README.md" {
			continue
		}
		name := base(md)
		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(md) //nolint:gosec // test-owned fixture path
			if err != nil {
				t.Fatal(err)
			}
			want, err := os.ReadFile(filepath.Join("testdata", name+".json")) //nolint:gosec // test-owned fixture path
			if err != nil {
				t.Fatalf("missing golden file: %v", err)
			}
			root, meta, err := Parse(src)
			if err != nil {
				t.Fatalf("Parse: %v", err)
			}
			got, err := treejson.Canonical(root)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("mdast JSON differs from golden:\n%s", treejson.FirstDiff(want, got))
			}
			checkMeta(t, name, meta)
		})
	}
}

func base(path string) string {
	b := filepath.Base(path)
	return b[:len(b)-len(filepath.Ext(b))]
}

// checkMeta compares the frontmatter a fixture returned against its golden
// <name>.meta.json. A fixture without that file must return an empty map, which
// covers every non-frontmatter fixture and the malformed-frontmatter case.
func checkMeta(t *testing.T, name string, meta map[string]any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name+".meta.json")) //nolint:gosec // test-owned fixture path
	if err != nil {
		if len(meta) != 0 {
			t.Errorf("no %s.meta.json but Parse returned metadata %v", name, meta)
		}
		return
	}
	var want any
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatalf("meta golden: %v", err)
	}
	gotJSON, err := treejson.Canonical(meta)
	if err != nil {
		t.Fatalf("marshal meta: %v", err)
	}
	wantJSON, err := treejson.Indent(want)
	if err != nil {
		t.Fatalf("marshal meta golden: %v", err)
	}
	if !bytes.Equal(gotJSON, wantJSON) {
		t.Errorf("metadata differs from golden:\n%s", treejson.FirstDiff(wantJSON, gotJSON))
	}
}

// TestListItemSpread locks the spread rule for a case the golden fixtures do
// not exercise: a list item whose own block children are separated by a blank
// line is spread, while an item with adjacent children (a paragraph and a
// nested list) is not.
func TestListItemSpread(t *testing.T) {
	src := []byte("- first\n\n  second\n\n- lone\n  - nested\n")
	root, _, err := Parse(src)
	if err != nil {
		t.Fatal(err)
	}
	list, ok := root.Children[0].(*MdastList)
	if !ok {
		t.Fatalf("first child is %T, want *MdastList", root.Children[0])
	}
	spreads := make([]bool, len(list.Children))
	for i, c := range list.Children {
		li, ok := c.(*MdastListItem)
		if !ok {
			t.Fatalf("list child %d is %T, want *MdastListItem", i, c)
		}
		spreads[i] = li.Spread
	}
	want := []bool{true, false}
	if len(spreads) != len(want) || spreads[0] != want[0] || spreads[1] != want[1] {
		t.Errorf("item spreads = %v, want %v", spreads, want)
	}
}

// BenchmarkParsePage parses the realistic page fixture.
func BenchmarkParsePage(b *testing.B) {
	src, err := os.ReadFile(filepath.Join("testdata", "page.md"))
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.SetBytes(int64(len(src)))
	for b.Loop() {
		if _, _, err := Parse(src); err != nil {
			b.Fatal(err)
		}
	}
}
