// Package hast converts an [mdast] tree into a [hast] tree: the HTML-shaped
// syntax tree the rehype ecosystem uses. Where mdast is Markdown-shaped
// (paragraphs, emphasis, list items), hast is HTML-shaped — `element` nodes
// with a `tagName`, `properties`, and `children`. A site renders a hast tree by
// switching on `tagName`; it needs no Markdown tooling.
//
// The conversion reproduces mdast-util-to-hast at the version pinned in the web
// workspace, byte for byte, verified against the golden fixtures in
// internal/mdast/testdata/*.hast.json (generated by web/scripts/mdast-fixtures.mjs).
// Two options deviate from that library's defaults; both are described in the
// README:
//
//   - raw HTML is passed through (an mdast `html` node becomes a hast `raw`
//     node) rather than dropped, matching format=mdast;
//   - a fenced code block's `meta` is kept as the `dataMeta` property (rendered
//     `data-meta`) rather than discarded.
//
// The package is a leaf: it imports internal/mdast and the standard library,
// nothing else.
//
// # Struct tags
//
// Like internal/mdast, the node types carry rocco schema tags so the OpenAPI
// spec (and the generated SDK) describes the tree as a typed, discriminated
// union: each Type field is a const of its node name, and each children field
// is a union over the four content node types, discriminated by that type.
// The tags are inert strings — the package still imports nothing outside
// internal/mdast and the standard library.
//
// The Go type names carry a Hast prefix so their generated schema names do not
// collide with the internal/mdast node schemas (rocco names a schema after the
// bare Go type name, and both trees have a root and a text node). The JSON
// `type` values are the unprefixed hast names (`root`, `element`, `text`,
// `comment`, `raw`).
//
// [mdast]: https://github.com/syntax-tree/mdast
// [hast]: https://github.com/syntax-tree/hast
package hast

// HastNode is a node in a hast tree. The set of implementations is closed — the
// interface's method is unexported, so only this package defines node types.
type HastNode interface {
	hastNode()
}

// HastRoot is the document root. It is the tree returned by FromMdast.
type HastRoot struct {
	Type     string     `json:"type" const:"root"`
	Children []HastNode `json:"children" discriminate:"HastElement,HastText,HastComment,HastRaw" discriminated_by:"type"`
}

// HastElement is an HTML element: a tag name, its properties (attributes, in
// hast's property spelling — className, htmlFor, dataMeta), and its children.
type HastElement struct {
	Type       string         `json:"type" const:"element"`
	TagName    string         `json:"tagName"`
	Properties map[string]any `json:"properties"`
	Children   []HastNode     `json:"children" discriminate:"HastElement,HastText,HastComment,HastRaw" discriminated_by:"type"`
}

// HastText is a run of text.
type HastText struct {
	Type  string `json:"type" const:"text"`
	Value string `json:"value"`
}

// HastComment is an HTML comment. FromMdast does not produce comment nodes —
// they arise only from parsing raw HTML, which this package does not do — but
// the type is part of the hast content union a renderer must accept.
type HastComment struct {
	Type  string `json:"type" const:"comment"`
	Value string `json:"value"`
}

// HastRaw is a run of raw HTML, passed through from an mdast `html` node. It is
// not standard hast: a renderer either emits it verbatim (trusted content) or
// runs it through an HTML parser to turn it into elements. The consumer decides
// whether to sanitise.
type HastRaw struct {
	Type  string `json:"type" const:"raw"`
	Value string `json:"value"`
}

func (*HastRoot) hastNode()    {}
func (*HastElement) hastNode() {}
func (*HastText) hastNode()    {}
func (*HastComment) hastNode() {}
func (*HastRaw) hastNode()     {}
